### PR TITLE
Build with latest Stackage LTS (16.4)

### LINKED ISSUE #6: Doctests fail with Stackage LTS 9.0
I believe this is a tooling issue rather than a true test failure.

Full build log from Travis CI here:
[https://travis-ci.org/github/pepeiborra/hexml-lens/builds/705181796](https://travis-ci.org/github/pepeiborra/hexml-lens/builds/705181796)

Relevant excerpt:

```
hexml-lens> test (suite: doctests)

### Failure in src/Text/XML/Hexml/Lens.hs:42: expression `"<?xml version=\"1.0\"?><foo/>" ^? _XML'
expected: Just Node "<?xml version=\"1.0\"?><foo/>"
 but got: 
          <interactive>:39:33: error:
              • Variable not in scope: (^?) :: [Char] -> t0 -> t
              • Perhaps you meant one of these:
                  ‘^’ (imported from Prelude), ‘^^’ (imported from Prelude)         

          <interactive>:39:36: error:
              • Found hole: _XML :: t0
                Where: ‘t0’ is an ambiguous type variable
                Or perhaps ‘_XML’ is mis-spelled, or not in scope
              • In the second argument of ‘(^?)’, namely ‘_XML’
                In the expression: (^?) "<?xml version=\"1.0\"?><foo/>" _XML
                In an equation for ‘it’:
                    it = (^?) "<?xml version=\"1.0\"?><foo/>" _XML
              • Relevant bindings include it :: t (bound at <interactive>:39:1)
Examples: 10  Tried: 4  Errors: 0  Failures: 1

hexml-lens> Test suite doctests failed
```

### PR DESCRIPTION
**Pull request by griggt**
Fixes doctest failures.

Closes #6

### CODE REVIEW

**Comment by pepeiborra** [comment]
Awesome, thanks!
